name: Build and Create Releases

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  build-windows:
    permissions: write-all
    runs-on: windows-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4

      - name: Setup application.properties
        shell: bash
        run: echo "api.base.url=${{ secrets.API_BASE_URL }}" > composeApp/src/jvmMain/resources/application.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build .msi
        run: ./gradlew composeApp:packageReleaseMsi

      - name: Get Version Name
        id: get_version_name
        shell: bash
        run: echo "version_name=$(./.github/scripts/get_version_name.sh versions.properties)" >> $GITHUB_OUTPUT

      - name: Upload Release MSI Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.output1 }}
          asset_path: composeApp/build/compose/binaries/main-release/msi/MrpackInstaller-${{ steps.get_version_name.outputs.version_name }}.msi
          asset_name: MrpackInstaller-${{ github.ref_name }}.msi
          asset_content_type: application/octet-stream

  build-macos:
    permissions: write-all
    runs-on: macos-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4

      - name: Setup application.properties
        run: echo "api.base.url=${{ secrets.API_BASE_URL }}" > composeApp/src/jvmMain/resources/application.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build .dmg
        run: ./gradlew composeApp:packageReleaseDmg

      - name: Get Version Name
        id: get_version_name
        shell: bash
        run: |
          chmod +x ./.github/scripts/get_version_name.sh
          echo "version_name=$(./.github/scripts/get_version_name.sh versions.properties)" >> $GITHUB_OUTPUT

      - name: Upload Release DMG Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.output1 }}
          asset_path: composeApp/build/compose/binaries/main-release/dmg/MrpackInstaller-${{ steps.get_version_name.outputs.version_name }}.dmg
          asset_name: MrpackInstaller-${{ github.ref_name }}.dmg
          asset_content_type: application/octet-stream

  build-linux:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4

      - name: Setup application.properties
        run: echo "api.base.url=${{ secrets.API_BASE_URL }}" > composeApp/src/jvmMain/resources/application.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install packaging tools
        run: sudo apt-get update && sudo apt-get install -y fakeroot dpkg rpm

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build .deb
        run: ./gradlew composeApp:packageReleaseDeb

      - name: Build .rpm
        run: ./gradlew composeApp:packageReleaseRpm

      - name: Get Version Name
        id: get_version_name
        shell: bash
        run: |
          chmod +x ./.github/scripts/get_version_name.sh
          echo "version_name=$(./.github/scripts/get_version_name.sh versions.properties)" >> $GITHUB_OUTPUT

      - name: Upload Release DEB Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.output1 }}
          asset_path: composeApp/build/compose/binaries/main-release/deb/MrpackInstaller-${{ steps.get_version_name.outputs.version_name }}.deb
          asset_name: MrpackInstaller-${{ github.ref_name }}.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Release RPM Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.output1 }}
          asset_path: composeApp/build/compose/binaries/main-release/rpm/MrpackInstaller-${{ steps.get_version_name.outputs.version_name }}.rpm
          asset_name: MrpackInstaller-${{ github.ref_name }}.rpm
          asset_content_type: application/x-rpm